M48
; DRILL file {KiCad (6.0.8)} date Mon Dec  5 17:54:39 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-05T17:54:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
%
G90
G05
T1
X105.954Y-36.83
X105.956Y-33.78
X160.336Y-36.83
X160.336Y-39.88
T0
M30
