onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top_flowambiguity_tb/files_recreated
add wave -noupdate /top_flowambiguity_tb/ctrl_input_emulation_mode
add wave -noupdate /top_flowambiguity_tb/ctrl_sim_start
add wave -noupdate /top_flowambiguity_tb/laser_clk
add wave -noupdate /top_flowambiguity_tb/sys_clk_p
add wave -noupdate /top_flowambiguity_tb/sys_clk_n
add wave -noupdate /top_flowambiguity_tb/led
add wave -noupdate /top_flowambiguity_tb/input_pads
add wave -noupdate /top_flowambiguity_tb/output_pads
add wave -noupdate /top_flowambiguity_tb/o_eom_ctrl_pulse
add wave -noupdate /top_flowambiguity_tb/o_eom_ctrl_pulsegen_busy
add wave -noupdate /top_flowambiguity_tb/o_debug_port_1
add wave -noupdate /top_flowambiguity_tb/o_debug_port_2
add wave -noupdate /top_flowambiguity_tb/o_debug_port_3
add wave -noupdate /top_flowambiguity_tb/readout_clk
add wave -noupdate /top_flowambiguity_tb/readout_data_ready
add wave -noupdate /top_flowambiguity_tb/readout_data_valid
add wave -noupdate /top_flowambiguity_tb/readout_enable
add wave -noupdate /top_flowambiguity_tb/readout_data_32b
add wave -noupdate /top_flowambiguity_tb/s_qubits
add wave -noupdate /top_flowambiguity_tb/s_photon_trans_event
add wave -noupdate /top_flowambiguity_tb/s_photon_value_latched
add wave -noupdate /top_flowambiguity_tb/s_photons_allcombinations_acc
add wave -noupdate /top_flowambiguity_tb/s_allphotons_transmitted_cnt
add wave -noupdate /top_flowambiguity_tb/s_qubits_transmitted_cnt
add wave -noupdate /top_flowambiguity_tb/s_photons_sampled_in_flow
add wave -noupdate /top_flowambiguity_tb/s_io_delay_upper_bound_ns
add wave -noupdate /top_flowambiguity_tb/s_io_delay_lower_bound_ns
add wave -noupdate /top_flowambiguity_tb/s_io_delay_avg_ns
add wave -noupdate /top_flowambiguity_tb/s_i_to_fsm_feedfwd_delay_lower_bound_ns
add wave -noupdate /top_flowambiguity_tb/s_i_to_fsm_feedfwd_delay_upper_bound_ns
add wave -noupdate /top_flowambiguity_tb/s_i_to_fsm_feedfwd_delay_avg_ns
add wave -noupdate /top_flowambiguity_tb/int_successful_flows_counter
add wave -noupdate /top_flowambiguity_tb/int_failed_flows_counter
add wave -noupdate /top_flowambiguity_tb/readout_photons
add wave -noupdate /top_flowambiguity_tb/readout_alpha
add wave -noupdate /top_flowambiguity_tb/readout_random
add wave -noupdate /top_flowambiguity_tb/readout_modulo
add wave -noupdate /top_flowambiguity_tb/readout_timestamps
add wave -noupdate /top_flowambiguity_tb/readout_csv1_line_done_event
add wave -noupdate /top_flowambiguity_tb/readout_coincidences
add wave -noupdate /top_flowambiguity_tb/readout_csv2_line_done_event
add wave -noupdate /top_flowambiguity_tb/readout_photon_counter
add wave -noupdate /top_flowambiguity_tb/readout_photon_losses
add wave -noupdate /top_flowambiguity_tb/readout_csv3_line_done_event
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sys_clk_p
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sys_clk_n
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/readout_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/readout_data_ready
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/readout_data_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/readout_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/readout_data_32b
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/led
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/o_photon_1v_before_cdcc
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/o_eom_ctrl_pulsegen_busy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_led_fifo_full_latched
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_fifo_wr_valid_qubit_flags
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_usb_fifo_empty
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_usb_fifo_full
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_usb_fifo_prog_empty
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/acq_clk90
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eval_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inemul_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/apd_emul_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/mmcm_locked
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_idelay_rdy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_idelay_rst
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_mmcm_not_locked
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_pads_v
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_v_fdre
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_v_iddr_2clk_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_v_iserdese2_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_pads_h
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_h_fdre
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_h_iddr_2clk_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_h_iserdese2_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_input_channels_donttouch
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/s_channels_redge_to_cdcc
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/s_valid_qubits_stable_to_cdcc
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_inemul_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_cdcc_rd_valid_to_fsm
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_cdcc_rd_qubits_to_fsm_delayed
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_feedfwd_success_flag
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_alpha_to_math
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_sx_sz_to_math
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_actual_qubit
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_actual_qubit_time_stamp
add wave -noupdate -color Magenta -expand -subitemconfig {/top_flowambiguity_tb/dut_top_flowambiguity/state_feedfwd(3) {-color Magenta -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/state_feedfwd(2) {-color Magenta -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/state_feedfwd(1) {-color Magenta -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/state_feedfwd(0) {-color Magenta -height 15}} /top_flowambiguity_tb/dut_top_flowambiguity/state_feedfwd
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_pseudorandom_to_math
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_math_data_modulo
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_math_data_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eom_ctrl_pulse_ready
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eom_ctrl_pulse_ready_delayed
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eom_ctrl_pulse_busy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eom_ctrl_pulse_busy_delayed
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_qubit_buffer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_time_stamp_buffer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_alpha_buffer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_modulo_buffer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_random_buffer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_photon_losses_to_cdcc
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_photon_losses
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_channels_detections_cntr
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_qubit_buffer_transferred_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_time_stamp_buffer_transferred_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_alpha_buffer_transferred_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_modulo_buffer_transferred_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_random_buffer_transferred_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_eom_ctrl_pulse
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_eom_ctrl_pulsegen_busy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_photon_1h
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_photon_1v
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_actual_qubit_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_feedforward_pulse
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_feedfwd_eom_pulse
add wave -noupdate -expand /top_flowambiguity_tb/dut_top_flowambiguity/slv_feedfwd_eom_pulse_delayed
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_feedfwd_start
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_feedfwd_start
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_rst
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/rd_rst
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_sys_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_channels_detections
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_photon_losses
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_valid_feedfwd_success_done
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_data_qubit_buffer
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_data_time_stamp_buffer
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_data_alpha_buffer
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_data_modulo_buffer
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_data_random_buffer
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/readout_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/readout_data_ready
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/readout_data_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/readout_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/readout_data_32b
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/fifo_full
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/fifo_empty
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/fifo_prog_empty
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/fifo_full_latched
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_time_now
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_time_feedfwd_sample_request
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_time_periodic_sample_request
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_time_periodic_sample_request_2
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/rst_wr_and_rd
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/wr_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_wr_en
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_wr_data
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/rd_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_rd_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_rd_data_out
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_full
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_empty
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_prog_empty
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_wr_en_flag_pulsed
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_wr_data_stream_32b
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_full_latched
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/int_periodic_report_counter
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_periodic_report_flag
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_readout_request_periodic
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_periodic_report_sample_request
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/int_periodic_report_counter_2
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_periodic_report_flag_2
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_readout_request_periodic_2
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_periodic_report_sample_request_2
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_combinations_counters_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_higher_bits_qubit_buffer
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_all_channels_detections_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_overflow_counter
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_last_bit_p1
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_all_unsuccessful_coincidences_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/int_readout_counter
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_combinations_counters_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_ch_detections_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_photon_losses_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_photons_buffer_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_alpha_buffer_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_modulo_buffer_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_random_buffer_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_timestamp_buffer_sampled
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_combinations_counters_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_ch_detections_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_photon_losses_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_photons_buffer_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_alpha_buffer_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_modulo_buffer_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_random_buffer_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/slv_flow_timestamp_buffer_shreg
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_readout_request_feedfwd
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_coincidences_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_ch_detections_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_photon_losses_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_photons_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_alpha_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_modulo_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_random_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/sl_request_read_timestamp_shift_enable
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/inst_csv_readout/state_fifo_readout
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/acq_clk0
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/dsp_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/s_stable_channels_to_cdcc
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_cdcc_rd_qubits_to_fsm
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_feedfwd_success_done_transferred
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_rst_eval_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_rst_readout_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/sl_rst_dsp_clk
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eom_ctrl_pulse_coincidence
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/eom_ctrl_pulse_coincidence(0)
add wave -noupdate -color Yellow -expand -subitemconfig {/top_flowambiguity_tb/dut_top_flowambiguity/input_pads(7) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(6) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(5) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(4) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(3) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(2) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(1) {-color Yellow -height 15} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads(0) {-color Yellow -height 15}} /top_flowambiguity_tb/dut_top_flowambiguity/input_pads
add wave -noupdate -expand -subitemconfig {/top_flowambiguity_tb/slv_cdcc_rd_qubits_to_fsm(1) {-color Red -height 15}} /top_flowambiguity_tb/slv_cdcc_rd_qubits_to_fsm
add wave -noupdate -expand /top_flowambiguity_tb/dut_top_flowambiguity/slv_o_sx_next_to_math
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/o_debug_port_1
add wave -noupdate -color {Medium Violet Red} /top_flowambiguity_tb/dut_top_flowambiguity/o_debug_port_2
add wave -noupdate -color {Cornflower Blue} /top_flowambiguity_tb/dut_top_flowambiguity/o_debug_port_3
add wave -noupdate -color {Orange Red} /top_flowambiguity_tb/dut_top_flowambiguity/o_eom_ctrl_pulse
add wave -noupdate -divider Queue
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_qubit_buffer_to_transfer_rd_valid
add wave -noupdate -expand /top_flowambiguity_tb/dut_top_flowambiguity/slv_time_stamp_buffer_to_transfer_rd_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_alpha_buffer_to_transfer_rd_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_modulo_buffer_to_transfer_rd_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_random_buffer_to_transfer_rd_valid
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_qubit_buffer_to_transfer_rd_rdy
add wave -noupdate -expand /top_flowambiguity_tb/dut_top_flowambiguity/slv_time_stamp_buffer_to_transfer_rd_rdy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_alpha_buffer_to_transfer_rd_rdy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_modulo_buffer_to_transfer_rd_rdy
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_random_buffer_to_transfer_rd_rdy
add wave -noupdate -expand /top_flowambiguity_tb/dut_top_flowambiguity/slv_qubit_buffer_to_transfer_2d
add wave -noupdate -expand /top_flowambiguity_tb/dut_top_flowambiguity/slv_time_stamp_buffer_to_transfer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_alpha_buffer_to_transfer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_modulo_buffer_to_transfer_2d
add wave -noupdate /top_flowambiguity_tb/dut_top_flowambiguity/slv_random_buffer_to_transfer_2d
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {9157749 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 549
configure wave -valuecolwidth 164
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {50071414 ps} {51322663 ps}
