puts $new_file_sim "    // This file serves for grouping the signals; This interface is without modport and clocking block"
puts $new_file_sim ""
puts $new_file_sim "    interface intf ("
puts $new_file_sim "        input logic clk, "
puts $new_file_sim "        input logic reset);"
puts $new_file_sim ""
puts $new_file_sim "        // Declare the signals to be grouped"
puts $new_file_sim "        logic valid;"
puts $new_file_sim "        logic \[3:0] a;"
puts $new_file_sim "        logic \[3:0] b;"
puts $new_file_sim "        logic \[3:0] c;"
puts $new_file_sim ""
puts $new_file_sim "    endinterface"