puts $new_file_sim "    // Scoreboard receives the sampled packet from the monitor and compares it with the expected result"
puts $new_file_sim "    // An error will be reported if the comparison results in a mismatch"
puts $new_file_sim ""
puts $new_file_sim "    // Declare scoreboard class"
puts $new_file_sim "    class scoreboard;"
puts $new_file_sim "        "
puts $new_file_sim "        // Create mailbox handle"
puts $new_file_sim "        mailbox mail_monitor2scbd;"
puts $new_file_sim "        "
puts $new_file_sim "        // Used to count the number of transactions"
puts $new_file_sim "        int trans_cnt;"
puts $new_file_sim "        "
puts $new_file_sim "        // Constructor"
puts $new_file_sim "        function new(mailbox mail_monitor2scbd);"
puts $new_file_sim "            // Getting the mailbox handles from Environment"
puts $new_file_sim "            this.mail_monitor2scbd = mail_monitor2scbd;"
puts $new_file_sim "        endfunction"
puts $new_file_sim "        "
puts $new_file_sim "        // Compare the Actual result with the expected result"
puts $new_file_sim "        task main;"
puts $new_file_sim "            transaction trans;"
puts $new_file_sim "            forever begin"
puts $new_file_sim "                mail_monitor2scbd.get(trans);"
puts $new_file_sim "                    if((trans.a+trans.b) == trans.c)"
puts $new_file_sim "                        \$display(\"Result is as Expected\");"
puts $new_file_sim "                    else"
puts $new_file_sim "                        \$error(\"Wrong Result.\\n\\tExpeced: %0d Actual: %0d\", (trans.a+trans.b),trans.c);"
puts $new_file_sim "                    trans_cnt++;"
puts $new_file_sim "                trans.display(\"\[ Scoreboard ]\");"
puts $new_file_sim "            end"
puts $new_file_sim "        endtask"
puts $new_file_sim "    "
puts $new_file_sim "    endclass"