puts $new_file_sim "    // Sample the interface signals and convert the signal level activity to the transaction level"
puts $new_file_sim "    // Send the sampled transaction to Scoreboard via Mailbox"
puts $new_file_sim ""
puts $new_file_sim "    // Declare monitor class"
puts $new_file_sim "    class monitor;"
puts $new_file_sim "    "
puts $new_file_sim "        // Create virtual interface handle"
puts $new_file_sim "        virtual intf virt_intf;"
puts $new_file_sim "        "
puts $new_file_sim "        // Create mailbox handle"
puts $new_file_sim "        mailbox mail_monitor2scbd;"
puts $new_file_sim "        "
puts $new_file_sim "        // Constructor"
puts $new_file_sim "        function new ("
puts $new_file_sim "            virtual intf virt_intf, mailbox mail_monitor2scbd);"
puts $new_file_sim "            // Get the interface"
puts $new_file_sim "            this.virt_intf = virt_intf;"
puts $new_file_sim "            // Get the mailbox handles from environment"
puts $new_file_sim "            this.mail_monitor2scbd = mail_monitor2scbd;"
puts $new_file_sim "        endfunction"
puts $new_file_sim "        "
puts $new_file_sim "        // Sample the interface signal and send the sample packet to scoreboard"
puts $new_file_sim "        task main;"
puts $new_file_sim "            forever begin"
puts $new_file_sim "                transaction trans;"
puts $new_file_sim "                trans = new();"
puts $new_file_sim "                @(posedge virt_intf.clk);"
puts $new_file_sim "                wait(virt_intf.valid);"
puts $new_file_sim "                trans.a = virt_intf.a;"
puts $new_file_sim "                trans.b = virt_intf.b;"
puts $new_file_sim "                @(posedge virt_intf.clk);"
puts $new_file_sim "                trans.c = virt_intf.c;"
puts $new_file_sim "                @(posedge virt_intf.clk);"
puts $new_file_sim "                mail_monitor2scbd.put(trans);"
puts $new_file_sim "                trans.display(\"\[ Monitor ]\");"
puts $new_file_sim "            end"
puts $new_file_sim "        endtask"
puts $new_file_sim "    "
puts $new_file_sim "    endclass"