puts $new_file_sim "    // Test code serves for creating the environment, configuring the testbench (setting the type, number of transactions)"
puts $new_file_sim "    // and executing the stimulus for driving the DUT"
puts $new_file_sim ""
puts $new_file_sim "    `include \"${name_file}_env.sv\""
puts $new_file_sim "    program test(intf intf);"
puts $new_file_sim "        "
puts $new_file_sim "        // Declare environment instance"
puts $new_file_sim "        environment env;"
puts $new_file_sim "        "
puts $new_file_sim "        initial begin"
puts $new_file_sim "            // Create environment"
puts $new_file_sim "            env = new(intf);"
puts $new_file_sim "            "
puts $new_file_sim "            // Set the repeat count of generator as 10, means to generate 10 packets"
puts $new_file_sim "            env.gen.repeat_count = 10;"
puts $new_file_sim "            "
puts $new_file_sim "            // Call run() of env, it calls generator and driver main tasks."
puts $new_file_sim "            env.run();"
puts $new_file_sim "        end"
puts $new_file_sim "    endprogram"