# This file generates a template of a HDL source file (VHDL)

puts $new_file_src ""
puts $new_file_src "    -- ${name_file}.${suffix_file}: <brief description>"
puts $new_file_src "    -- Engineer: $engineer_name"
puts $new_file_src "    -- Email: $email_addr"
set clock_seconds [clock seconds]
set act_date [clock format $clock_seconds -format %D]
# puts $new_file_src "    -- Created: $act_date"
puts $new_file_src ""
puts $new_file_src "    library ieee;"
puts $new_file_src "    use ieee.std_logic_1164.all;"
puts $new_file_src "    use ieee.numeric_std.all;"
puts $new_file_src "    -- use ieee.math_real.all;"
puts $new_file_src "    -- use ieee.math_complex.all;"
puts $new_file_src ""
puts $new_file_src "    -- Additional project-specific packages (src)"
puts $new_file_src "    library $file_library_src;"
puts $new_file_src "    use $file_library_src.const_pack.all;"
puts $new_file_src "    use $file_library_src.gtypes_pack.all;"
puts $new_file_src "    use $file_library_src.signals_pack.all;"
puts $new_file_src ""
puts $new_file_src "    entity $name_file is"
puts $new_file_src "        generic ("
puts $new_file_src "            DATA_WIDTH : natural := 8;"
puts $new_file_src "            DATA_LENGTH : natural := 32"
puts $new_file_src "        );"
puts $new_file_src "        port ("
puts $new_file_src "            clk : in std_logic;"
puts $new_file_src "            rst : in std_logic;"
puts $new_file_src ""
puts $new_file_src "            ${name_file}_rdy      : out std_logic;"
puts $new_file_src "            ${name_file}_valid    : out std_logic;"
puts $new_file_src "            ${name_file}_ack      : out std_logic;"
puts $new_file_src "            out_port : out std_logic"
puts $new_file_src "        );"
puts $new_file_src "    end entity;"
puts $new_file_src ""
puts $new_file_src "    architecture $file_arch of $name_file is"
puts $new_file_src ""
puts $new_file_src "        ---------------------------------------------"
puts $new_file_src "        -- Declaration of Subtypes/Types/Constants --"
puts $new_file_src "        ---------------------------------------------"
puts $new_file_src ""
puts $new_file_src "        ----------------------------"
puts $new_file_src "        -- Declaration of Signals --"
puts $new_file_src "        ----------------------------"
puts $new_file_src ""
puts $new_file_src "    begin"
puts $new_file_src ""
puts $new_file_src "        -----------------------"
puts $new_file_src "        -- User Architecture --"
puts $new_file_src "        -----------------------"
puts $new_file_src ""
puts $new_file_src "        --------------------------------"
puts $new_file_src "        -- Unsupported Generics Check --"
puts $new_file_src "        --------------------------------"
puts $new_file_src ""
puts -nonewline $new_file_src "    end architecture;"