M48
; DRILL file {KiCad (6.0.8)} date Fri Oct 28 14:48:36 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-28T14:48:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0402
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.6988Y-5.2201
X7.0012Y-5.2201
T2
X3.5Y-3.0
X3.5Y-5.5
X7.5Y-3.0
X7.5Y-5.5
T0
M30
