onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {TB: universal_readout_tb ALL signals}
add wave -noupdate /csv_readout_tb/files_recreated
add wave -noupdate /csv_readout_tb/rst
add wave -noupdate /csv_readout_tb/wr_valid_feedfwd_success_done
add wave -noupdate /csv_readout_tb/wr_data_qubit_buffer
add wave -noupdate /csv_readout_tb/wr_data_time_stamp_buffer
add wave -noupdate /csv_readout_tb/wr_data_alpha_buffer
add wave -noupdate /csv_readout_tb/wr_data_modulo_buffer
add wave -noupdate /csv_readout_tb/wr_data_random_buffer
add wave -noupdate /csv_readout_tb/readout_enable
add wave -noupdate /csv_readout_tb/readout_data_ready
add wave -noupdate /csv_readout_tb/readout_data_valid
add wave -noupdate /csv_readout_tb/readout_data_32b
add wave -noupdate /csv_readout_tb/fifo_full
add wave -noupdate /csv_readout_tb/fifo_empty
add wave -noupdate /csv_readout_tb/fifo_prog_empty
add wave -noupdate /csv_readout_tb/fifo_full_latched
add wave -noupdate /csv_readout_tb/clk_wr
add wave -noupdate /csv_readout_tb/clk_rd
add wave -noupdate -divider DUT
add wave -noupdate /csv_readout_tb/dut_csv_readout/rst
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_sys_clk
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_valid_feedfwd_success_done
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_data_qubit_buffer
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_data_time_stamp_buffer
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_data_alpha_buffer
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_data_modulo_buffer
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_data_random_buffer
add wave -noupdate /csv_readout_tb/dut_csv_readout/readout_clk
add wave -noupdate /csv_readout_tb/dut_csv_readout/readout_data_ready
add wave -noupdate /csv_readout_tb/dut_csv_readout/readout_data_valid
add wave -noupdate /csv_readout_tb/dut_csv_readout/readout_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/readout_data_32b
add wave -noupdate /csv_readout_tb/dut_csv_readout/fifo_full
add wave -noupdate /csv_readout_tb/dut_csv_readout/fifo_empty
add wave -noupdate /csv_readout_tb/dut_csv_readout/fifo_prog_empty
add wave -noupdate /csv_readout_tb/dut_csv_readout/fifo_full_latched
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_rst
add wave -noupdate /csv_readout_tb/dut_csv_readout/wr_clk
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_wr_en
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_wr_data
add wave -noupdate /csv_readout_tb/dut_csv_readout/rd_clk
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_rd_valid
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_rd_data_out
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_full
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_empty
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_prog_empty
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_wr_en_flag_pulsed
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_wr_data_stream_32b
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_full_latched
add wave -noupdate /csv_readout_tb/dut_csv_readout/int_periodic_report_counter
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_periodic_report_flag
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_periodic_report_sample_request
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_combinations_counters_2d
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_higher_bits_qubit_buffer
add wave -noupdate /csv_readout_tb/dut_csv_readout/int_readout_counter
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_combinations_counters_sampled
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_photons_buffer_sampled
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_alpha_buffer_sampled
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_modulo_buffer_sampled
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_random_buffer_sampled
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_timestamp_buffer_sampled
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_combinations_counters_shreg
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_photons_buffer_shreg
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_alpha_buffer_shreg
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_modulo_buffer_shreg
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_random_buffer_shreg
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_flow_timestamp_buffer_shreg
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_readout_request_feedfwd
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_request_read_coincidences_shift_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_request_read_photons_shift_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_request_read_alpha_shift_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_request_read_modulo_shift_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_request_read_random_shift_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/sl_request_read_timestamp_shift_enable
add wave -noupdate /csv_readout_tb/dut_csv_readout/state_fifo_readout
add wave -noupdate -childformat {{/csv_readout_tb/dut_csv_readout/slv_all_channels_detections_2d(0) -radix unsigned}} -subitemconfig {/csv_readout_tb/dut_csv_readout/slv_all_channels_detections_2d(0) {-height 15 -radix unsigned}} /csv_readout_tb/dut_csv_readout/slv_all_channels_detections_2d
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_all_unsuccessful_coincidences_2d
add wave -noupdate /csv_readout_tb/dut_csv_readout/slv_last_bit_p1
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {7695000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 468
configure wave -valuecolwidth 204
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {42 us}
